openapi: 3.0.0
info:
  title: Almanarat API
  description: AL-manarat backend website
  version: 1.1.0
  contact:
    email: sasa97977s@hotmail.com
    url: "https://github.com/salehHadi?tab=repositories"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for localhost - secure
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost - regular

servers:
  - url: "{protocal}://localhost:4000/api/{version}"
    description: for localhost
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocal:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: anything
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /:
    get:
      tags:
        - String
      summary: Return a greeting message from Al-manarat
      responses:
        200: # status code
          description: All good & success
          content:
            application/json:
              schema:
                type: string
                example: " mystring"
        400:
          description: Bad request
        500:
          description: internel service err
